#!/bin/zsh

help="Usage: git fuzz <option> <args>\nd diff\nl log\na add\nc clean\nf files\ni ignore\ns stash\nr restore"

source $HOME/.oh-my-zsh/custom/plugins/forgit/forgit.plugin.zsh

case "$1" in
    d|diff)
        forgit::diff "${@:2}"
        exit 0
        ;;
    l|log)
        forgit::log "${@:2}"
        exit 0
        ;;
    a|add)
        forgit::add "${@:2}"
        exit 0
        ;;
    c|clean)
        forgit::clean "${@:2}"
        exit 0
        ;;
    f|files)
        forgit::fzf "${@:2}"
        exit 0
        ;;
    i|ignore)
        forgit:ignore "${@:2}"
        exit 0
        ;;
    s|stash)
        forgit::stash::show "${@:2}"
        exit 0
        ;;
    r|restore)
        forgit::restore "${@:2}"
        exit 0
        ;;
    *)
        echo $help
        exit 1
        ;;
esac
