#!/bin/bash
# Find and replace all strings in tracked files in a git repository
# USAGE: git %s <find_text> <replace_text> <args>

# escape any regexp chars used by sed
prepare() {
    sed -e 's/[]\/$*.^[]/\\&/g'
}
find_text=$(echo $1 | prepare)
replace_text=$(echo $2 | prepare)

# $1 is the find text, ${@:3} is the git flags, $2 is the replace text
git ${@:3} grep -l $1 | xargs sed -E "s/$find_text/$replace_text/g"
